=== danaAmin23/student-timetable/studentTimetable.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="fanshaweCollege">
    
   
        
          
    <xs:complexType>
      <xs:sequence>
        <xs:element name="studenttimetable">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="student">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="program" minOccurs="0" type="xs:string" />
                    <xs:element name="schoolName" minOccurs="0" type="xs:string" />
                    <xs:element name="term" type="xs:string" />
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="id" type="xs:unsignedInt" use="required" />
                </xs:complexType>
              </xs:element>
              <xs:element name="classes">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="course" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="5" minOccurs="5" name="dayofWeek">
                            <xs:complexType mixed="true">
                              <xs:sequence>
                                <xs:element name="hoursofClass" minOccurs="0">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element maxOccurs="13" minOccurs="0" name="hour">
                                        <xs:complexType>
                                          <xs:attribute name="hour"  use="required">
                                            <xs:simpleType>
                                            <xs:restriction>
                                              <xs:simpleType>
                                                <xs:restriction base="xs:unsignedShort">
                                                  <xs:pattern value="0800|0900|1000|1100|1200|1300|1400|1500|1600|1700|1800|1900|2000"/>
                                                  <xs:minInclusive value="0800"></xs:minInclusive>
                                                  <xs:maxInclusive value="2000"></xs:maxInclusive>
                                                </xs:restriction>
                                              </xs:simpleType>
                                            </xs:restriction>
                                            </xs:simpleType>
                                          </xs:attribute>
                                        </xs:complexType>
                                     
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="roomNumber" type="xs:string" minOccurs="0" />
                              </xs:sequence>
                              <xs:attribute name="id"  use="required" >
                                <xs:simpleType>
                                  <xs:restriction>
                                    <xs:simpleType>
                                      <xs:restriction base="xs:string">
                                        <xs:pattern value="Monday|Tuesday|Wednesday|Thursday|Friday"/>
                                      </xs:restriction>
                                    </xs:simpleType>
                                  </xs:restriction>
                                </xs:simpleType>      
                              </xs:attribute>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="code" type="xs:string" use="required" />
                      </xs:complexType>
                      <xs:unique name ="uniqueDay">
                        <xs:selector xpath="dayofWeek"></xs:selector>
                        <xs:field xpath ="@id"></xs:field>
                      </xs:unique>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== danaAmin23/student-timetable/ValidOne.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Project 1 -->
<fanshaweCollege
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="studentTimetable.xsd">

  <studenttimetable>
    <student name="Jody Cooper" id = "9121211">
      <program>Business Accounting (Co-op)</program>
      <schoolName>Fanshawe College, London Campus</schoolName>
      <term>W2018</term>
    </student>

    <classes>
      <!-- classes -->

      <course code="ACCT-3050-06">
        <dayofWeek id="Monday">

          <hoursofClass>
            <hour hour ='0800'></hour>
            <hour hour= '0900'></hour>
          </hoursofClass>
          <roomNumber>B1036</roomNumber>
        </dayofWeek>

  
        <dayofWeek id = "Wednesday">
          
          <hoursofClass>
            <hour hour ="0800"></hour>
            <hour hour="0900"></hour>
          </hoursofClass>
          <roomNumber>D2023</roomNumber>
        </dayofWeek>
      
            <dayofWeek id ="Tuesday"></dayofWeek>
      <dayofWeek id="Thursday"></dayofWeek>
      <dayofWeek id="Friday"></dayofWeek>

      
      </course>

      <!-- end class -->

      <course code="ACCT-3022-03">
        <dayofWeek id="Monday">
          <hoursofClass>
            <hour hour="1300"></hour>
          </hoursofClass>
          <roomNumber>D1015</roomNumber>
        </dayofWeek>

        <dayofWeek id ="Friday">
        
          <hoursofClass>
            <hour hour="1400"></hour>
            <hour hour="1500"></hour>
          </hoursofClass>
          <roomNumber>D1015</roomNumber>
        </dayofWeek>
        <dayofWeek id="Tuesday"></dayofWeek>
      <dayofWeek id="Wednesday"></dayofWeek>
      <dayofWeek id="Thursday"></dayofWeek>
      </course>

      
 <course code="SYST-3002-02">
        <dayofWeek id ="Monday">
          <hoursofClass>
            <hour hour="1400"></hour>
            <hour hour="1500"></hour>
          </hoursofClass>
          <roomNumber>D1015</roomNumber>
        </dayofWeek>

        <dayofWeek id="Friday">
          <hoursofClass>
            <hour hour ="1100"></hour>
          </hoursofClass>
          <roomNumber>F3004</roomNumber>
        </dayofWeek>
 
      <dayofWeek id="Tuesday"></dayofWeek>
      <dayofWeek id="Wednesday"></dayofWeek>
      <dayofWeek id="Thursday"></dayofWeek>
 
      </course>


      <course code="FINA-3044-01">
        <dayofWeek id="Tuesday">
          
          <hoursofClass>
            <hour hour ="0900"></hour>
            <hour hour="1000"></hour>
            <hour hour="1100"></hour>
          </hoursofClass>
          <roomNumber>H2004</roomNumber>
        </dayofWeek>
        
      <dayofWeek id="Monday"></dayofWeek>
      <dayofWeek id="Wednesday"></dayofWeek>
      <dayofWeek id="Thursday"></dayofWeek>
       <dayofWeek id="Friday"></dayofWeek>
       
      </course>
      <course code="FINA-3042-03">
        <dayofWeek id="Wednesday">
          <hoursofClass>
            <hour hour ="1200"></hour>
            <hour hour="1300"></hour>
          </hoursofClass>
          <roomNumber>H2004</roomNumber>
        </dayofWeek>

        <dayofWeek id="Friday">
          <hoursofClass>
            <hour hour="1300"></hour>
          </hoursofClass>
          <roomNumber>H2002</roomNumber>
        </dayofWeek>
      
          <dayofWeek id="Monday"></dayofWeek>
      <dayofWeek id="Tuesday"></dayofWeek>
      <dayofWeek id="Thursday"></dayofWeek>
      
      </course>

      <course code="LAWS-3041-06">
        <dayofWeek id="Tuesday">
          <hoursofClass>
            <hour hour ="1500"></hour>

          </hoursofClass>
          <roomNumber>H2002</roomNumber>
        </dayofWeek>

        <dayofWeek id="Wednesday">
          <hoursofClass>
            <hour hour="1600"></hour>
            <hour hour="1700"></hour>

          </hoursofClass>
          <roomNumber>F3004</roomNumber>
        </dayofWeek>
        
        <dayofWeek id="Monday"></dayofWeek>
      <dayofWeek id="Friday"></dayofWeek>
      <dayofWeek id="Thursday"></dayofWeek>
      
      </course>
      <!--end courses-->
    </classes>
  </studenttimetable>
</fanshaweCollege>

=== danaAmin23/student-timetable/ValidTwo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Project 1 -->
<fanshaweCollege
  
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="studentTimetable.xsd">

  <studenttimetable>
    <student name="Dana Amin" id = "0819393">
      <program>IWD1</program>
      <schoolName>Fanshawe College, London Campus</schoolName>
      <term>W2018</term>
    </student>

    <classes>
      <!-- classes -->

      <course code="DTB-3090-01">
        <dayofWeek id ="Monday">
          <hoursofClass>
            <hour hour= "0800"></hour>
            <hour hour="0900"></hour>
          </hoursofClass>
          <roomNumber>B2029</roomNumber>
        </dayofWeek>

        <dayofWeek id="Wednesday">
          <hoursofClass>
            <hour hour="1100"></hour>
            <hour hour="1200"></hour>
          </hoursofClass>
          <roomNumber>M3045</roomNumber>
        </dayofWeek>
        
        <dayofWeek id="Tuesday"></dayofWeek>
        <dayofWeek id="Friday"></dayofWeek>
        <dayofWeek id="Thursday"></dayofWeek>



      </course>

      <!-- end class -->

      <course code="HTML-3000-03">
        <dayofWeek id="Tuesday">
          <hoursofClass>
            <hour hour="1200"></hour>
            <hour hour="1300"></hour>
          </hoursofClass>
          <roomNumber>G9054</roomNumber>
        </dayofWeek>

        <dayofWeek id="Thursday">
          <hoursofClass>
            <hour hour="1500"></hour>
            <hour hour="1600"></hour>
            <hour hour="1700"></hour>
          </hoursofClass>
          <roomNumber>B4006</roomNumber>
        </dayofWeek>

        <dayofWeek id="Monday"></dayofWeek>
        <dayofWeek id="Friday"></dayofWeek>
        <dayofWeek id="Wednesday"></dayofWeek>

      </course>

      <course code="CYST-1000-05">
        <dayofWeek id="Monday">
          <hoursofClass>
            <hour hour ="1200"></hour>
            <hour hour="1300"></hour>
          </hoursofClass>
          <roomNumber>D5091</roomNumber>
        </dayofWeek>

        <dayofWeek id="Wednesday">
          <hoursofClass>
            <hour hour="1500"></hour>
            <hour hour ="1600"></hour>
            <hour hour="1700"></hour>
          </hoursofClass>
          <roomNumber>S2045</roomNumber>
        </dayofWeek>

        <dayofWeek id="Tuesday"></dayofWeek>
        <dayofWeek id="Friday"></dayofWeek>
        <dayofWeek id="Thursday"></dayofWeek>


      </course>

      <course code="OOP1-4000-03">
        <dayofWeek id="Tuesday">
          
          <hoursofClass>
            <hour hour="0900"></hour>
            <hour hour="1000"></hour>
          </hoursofClass>
          <roomNumber>G9054</roomNumber>
        </dayofWeek>

        <dayofWeek id="Thursday">
                    <hoursofClass>
            <hour hour="0800"></hour>
            <hour hour ="0900"></hour>
          </hoursofClass>
          <roomNumber>R2045</roomNumber>
        </dayofWeek>

        <dayofWeek id="Monday"></dayofWeek>
        <dayofWeek id="Friday"></dayofWeek>
        <dayofWeek id="Wednesday"></dayofWeek>


      </course>

      <course code="MATH-3042-09">
        <dayofWeek id="Friday">
          
          <hoursofClass>
            <hour hour="1000"></hour>
            <hour hour="1100"></hour>
            <hour hour="1200"></hour>
          </hoursofClass>
          <roomNumber>W2001</roomNumber>
        </dayofWeek>

        <dayofWeek id="Monday"></dayofWeek>
        <dayofWeek id="Tuesday"></dayofWeek>
        <dayofWeek id="Thursday"></dayofWeek>
        <dayofWeek id="Wednesday"></dayofWeek>



      </course>






    </classes>
  </studenttimetable>
</fanshaweCollege>
